version: '3.8'

services:
  pharma-recognition:
    build: .
    image: pharma-recognition:latest
    container_name: pharma-recognition
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config:/app/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - FLAGS_fraction_of_gpu_memory_to_use=0.8
      - OMP_NUM_THREADS=6
      - OMP_WAIT_POLICY=ACTIVE
      - KMP_AFFINITY=granularity=fine,compact,1,0
    command: python3 src/main.py
    restart: unless-stopped
